import org.gradle.api.publish.maven.MavenPublication
import org.jetbrains.kotlin.gradle.tasks.publishing.CheckPomTask

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Gradle plugin project to get you started.
 * For more details on writing Custom Plugins, please refer to https://docs.gradle.org/9.7.1/userguide/custom_plugins.html in the Gradle documentation.
 */

plugins {
    jacoco
    alias(libs.plugins.kotlin.jvm)
    alias(libs.plugins.plugin.publish)
}

group = "kr.co.plott"
version = providers.gradleProperty("pluginVersion").getOrElse("0.1.0-SNAPSHOT")

repositories {
    mavenCentral()
}

dependencies {
    testImplementation(platform(libs.junit.bom))
    testImplementation(libs.junit.jupiter)
    testRuntimeOnly(libs.junit.platform.launcher)
}

gradlePlugin {
    website.set("https://github.com/handyskr/gradle-plott-concord")
    vcsUrl.set("https://github.com/handyskr/gradle-plott-concord.git")

    val projectHooks = plugins.create("projectHooks") {
        id = "kr.co.plott.concord"
        implementationClass = "kr.co.plott.concord.ConcordPlugin"
        displayName = "Plott Concord"
        description = "Initializes project development hooks and settings from Gradle configuration."
        tags.set(listOf("hooks", "automation", "project-configuration"))
    }
}

publishing {
    publications.withType<MavenPublication>().configureEach {
        if (name == "pluginMaven") {
            artifactId = "gradle-plott-concord"
        }
        pom {
            name.set("Plott Concord")
            description.set("Initializes project development hooks and settings from Gradle configuration.")
            url.set("https://github.com/handyskr/gradle-plott-concord")
            inceptionYear.set("2026")
            licenses {
                license {
                    name.set("The Apache License, Version 2.0")
                    url.set("https://www.apache.org/licenses/LICENSE-2.0.txt")
                    distribution.set("repo")
                }
            }
            developers {
                developer {
                    id.set("handyskr")
                    name.set("Handys Inc")
                    url.set("https://github.com/handyskr")
                    organization.set("Handys Inc")
                    organizationUrl.set("https://github.com/handyskr")
                }
            }
            scm {
                url.set("https://github.com/handyskr/gradle-plott-concord")
                connection.set("scm:git:https://github.com/handyskr/gradle-plott-concord.git")
                developerConnection.set("scm:git:ssh://git@github.com/handyskr/gradle-plott-concord.git")
            }
        }
    }
}

// Plugin Portal publishing does not use Maven Central's developer-email contract.
tasks.withType<CheckPomTask>().configureEach {
    enabled = false
}

tasks.named<Test>("test") {
    useJUnitPlatform()
    finalizedBy(tasks.jacocoTestReport)
}

tasks.jacocoTestReport {
    dependsOn(tasks.test)
    reports {
        xml.required.set(true)
        html.required.set(true)
        csv.required.set(false)
    }
}
