package kr.co.plott.concord

import kr.co.plott.concord.exception.InvalidConfigurationException
import kr.co.plott.concord.exception.ManagedFileConflictException
import java.nio.charset.StandardCharsets
import java.nio.file.AtomicMoveNotSupportedException
import java.nio.file.Files
import java.nio.file.Path
import java.nio.file.StandardCopyOption
import java.security.MessageDigest

internal class ManagedFileWriter {
    fun write(target: Path, content: ByteArray, executable: Boolean) {
        Files.createDirectories(target.parent)
        val stateDirectory = target.parent.resolve(STATE_DIRECTORY)
        refuseSymbolicLink(stateDirectory)
        if (Files.exists(stateDirectory) && !Files.isDirectory(stateDirectory)) {
            throw ManagedFileConflictException("Managed state path is not a directory: $stateDirectory")
        }
        Files.createDirectories(stateDirectory)
        val state = stateDirectory.resolve("${target.fileName}.sha256")

        refuseSymbolicLink(target)
        refuseSymbolicLink(state)
        if (Files.exists(state) && !Files.isRegularFile(state)) {
            throw ManagedFileConflictException("Managed state is not a regular file: $state")
        }
        refuseDivergedFile(target, state, content)

        if (!hasContent(target, content)) {
            writeAtomically(target, content)
        }
        setPermissions(target, executable)

        val desiredState = "${sha256(content)}\n".toByteArray()
        if (!hasContent(state, desiredState)) {
            writeAtomically(state, desiredState)
        }
    }

    private fun refuseDivergedFile(target: Path, state: Path, desiredContent: ByteArray) {
        if (Files.exists(target) && !Files.isRegularFile(target)) {
            throw ManagedFileConflictException("Managed path is not a regular file: $target")
        }
        if (!Files.isRegularFile(target)) {
            return
        }

        val currentContent = Files.readAllBytes(target)
        if (!Files.isRegularFile(state)) {
            val carriesLegacyMarker = currentContent.toString(StandardCharsets.UTF_8).startsWith(LEGACY_PREFIX)
            if (!currentContent.contentEquals(desiredContent) && !carriesLegacyMarker) {
                throw ManagedFileConflictException("Refusing to replace an unmanaged file: $target")
            }
            return
        }

        val managedHash = Files.readString(state).trim()
        if (managedHash != sha256(currentContent)) {
            throw ManagedFileConflictException("Refusing to replace a locally modified managed file: $target")
        }
    }

    private fun refuseSymbolicLink(path: Path) {
        if (Files.isSymbolicLink(path)) {
            throw ManagedFileConflictException("Refusing to replace a symbolic managed path: $path")
        }
    }

    private fun setPermissions(target: Path, executable: Boolean) {
        val file = target.toFile()
        val permissionsSet = file.setWritable(true, true) && file.setReadable(true, false) &&
            file.setExecutable(executable, false)
        if (!permissionsSet) {
            throw InvalidConfigurationException("Could not set permissions for managed file: $target")
        }
    }

    private fun hasContent(path: Path, content: ByteArray): Boolean =
        Files.isRegularFile(path) && Files.readAllBytes(path).contentEquals(content)

    private fun writeAtomically(path: Path, content: ByteArray) {
        val temporary = Files.createTempFile(path.parent, ".${path.fileName}.", ".tmp")
        try {
            Files.write(temporary, content)
            try {
                Files.move(
                    temporary,
                    path,
                    StandardCopyOption.ATOMIC_MOVE,
                    StandardCopyOption.REPLACE_EXISTING,
                )
            } catch (_: AtomicMoveNotSupportedException) {
                Files.move(temporary, path, StandardCopyOption.REPLACE_EXISTING)
            }
        } finally {
            Files.deleteIfExists(temporary)
        }
    }

    private fun sha256(content: ByteArray): String =
        MessageDigest.getInstance("SHA-256")
            .digest(content)
            .joinToString("") { byte -> "%02x".format(byte) }

    private companion object {
        const val STATE_DIRECTORY = ".plott-concord"
        const val LEGACY_PREFIX =
            "#!/bin/sh\n# Generated by Plott Concord. Configure it in build.gradle.kts."
    }
}
