package kr.co.plott.concord.git

import java.nio.charset.StandardCharsets

internal class CommandHookRenderer {
    fun render(command: String): ByteArray =
        """
        |#!/bin/sh
        |# Generated by Plott Concord. Configure it in build.gradle.kts.
        |
        |if ! $command; then
        |    printf '%s\n' 'Plott Concord Git hook failed; the Git operation will continue.' >&2
        |fi
        |
        |exit 0
        """.trimMargin().plus("\n").toByteArray(StandardCharsets.UTF_8)
}
