package kr.co.plott.concord

import kr.co.plott.concord.exception.ManagedFileConflictException
import org.junit.jupiter.api.Assertions.assertArrayEquals
import org.junit.jupiter.api.Assertions.assertThrows
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Assumptions.assumeFalse
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.io.TempDir
import java.nio.file.Files
import java.nio.file.Path

class ManagedFileWriterTest {
    @field:TempDir
    lateinit var directory: Path

    private val writer = ManagedFileWriter()

    @Test
    fun `writes content permissions and ownership state`() {
        val target = directory.resolve("hooks/pre-commit")
        val content = "hook".toByteArray()

        writer.write(target, content, executable = true)

        assertArrayEquals(content, Files.readAllBytes(target))
        assertTrue(Files.isReadable(target))
        assertTrue(Files.isExecutable(target))
        assertTrue(Files.isRegularFile(stateFor(target)))
    }

    @Test
    fun `takes ownership when existing content already matches`() {
        val target = directory.resolve("hooks/pre-commit")
        Files.createDirectories(target.parent)
        Files.writeString(target, "same")

        writer.write(target, "same".toByteArray(), executable = true)

        assertTrue(Files.isRegularFile(stateFor(target)))
    }

    @Test
    fun `can write a non-executable managed file`() {
        val target = directory.resolve("config/settings.json")

        writer.write(target, "{}".toByteArray(), executable = false)

        assertTrue(Files.isRegularFile(target))
    }

    @Test
    fun `updates a file that still matches managed state`() {
        val target = directory.resolve("hooks/pre-commit")
        writer.write(target, "first".toByteArray(), executable = true)

        writer.write(target, "second".toByteArray(), executable = true)

        assertArrayEquals("second".toByteArray(), Files.readAllBytes(target))
    }

    @Test
    fun `migrates a generated file from the marker based format`() {
        val target = directory.resolve("hooks/pre-commit")
        Files.createDirectories(target.parent)
        Files.writeString(
            target,
            "#!/bin/sh\n# Generated by Plott Concord. Configure it in build.gradle.kts.\nexit 0\n",
        )

        writer.write(target, "replacement".toByteArray(), executable = true)

        assertArrayEquals("replacement".toByteArray(), Files.readAllBytes(target))
    }

    @Test
    fun `refuses an unmanaged file with different content`() {
        val target = directory.resolve("hooks/pre-commit")
        Files.createDirectories(target.parent)
        Files.writeString(target, "local")

        assertThrows(ManagedFileConflictException::class.java) {
            writer.write(target, "managed".toByteArray(), executable = true)
        }
    }

    @Test
    fun `refuses a locally modified managed file`() {
        val target = directory.resolve("hooks/pre-commit")
        writer.write(target, "managed".toByteArray(), executable = true)
        Files.writeString(target, "local change")

        assertThrows(ManagedFileConflictException::class.java) {
            writer.write(target, "next".toByteArray(), executable = true)
        }
    }

    @Test
    fun `refuses symbolic and non-regular targets`() {
        assumeFalse(System.getProperty("os.name").startsWith("Windows"))
        val hooksDirectory = directory.resolve("hooks")
        Files.createDirectories(hooksDirectory)
        val source = Files.writeString(directory.resolve("source"), "local")
        val symbolicTarget = Files.createSymbolicLink(hooksDirectory.resolve("pre-commit"), source)

        assertThrows(ManagedFileConflictException::class.java) {
            writer.write(symbolicTarget, "managed".toByteArray(), executable = true)
        }

        val directoryTarget = Files.createDirectory(hooksDirectory.resolve("commit-msg"))
        assertThrows(ManagedFileConflictException::class.java) {
            writer.write(directoryTarget, "managed".toByteArray(), executable = true)
        }
    }

    private fun stateFor(target: Path): Path =
        target.parent.resolve(".plott-concord/${target.fileName}.sha256")
}
